
CXX = g++
CXXFLAGS = -std=c++0x
#add CPP files here
SCRS = Container.cpp FrontDoor.cpp Item.cpp Person.cpp Room.cpp Space.cpp Stairs.cpp Source.cpp 
#add HPP files here
HEADERS = Container.hpp FrontDoor.hpp Item.hpp Person.hpp Room.hpp Space.hpp Stairs.hpp


#
#
#
run: ${SCRS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SCRS} -o run
