
CXX = g++
CXXFLAGS = -std=c++0x

SCRS = destroyWorld.cpp initializeWorld.cpp main.cpp neighborCheck.cpp printWorld.cpp startShape.cpp worldSwap.cpp

HEADERS = destroyWorld.hpp initializeWorld.hpp neighborCheck.hpp printWorld.hpp startShape.hpp worldSwap.hpp


#
#
#
run: ${SCRS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SCRS} -o run
