
CXX = g++
CXXFLAGS = -std=c++0x
#add CPP files here
SCRS =  Barbarian.cpp BlueMen.cpp Creature.cpp Die.cpp HarryPotter.cpp List.cpp Medusa.cpp Queue.cpp Stack.cpp Vampire.cpp Source.cpp
#add HPP files here
HEADERS = Barbarian.hpp BlueMen.hpp Creature.hpp Die.hpp HarryPotter.hpp List.hpp Medusa.hpp Queue.hpp Stack.hpp Vampire.hpp 


#
#
#
run: ${SCRS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SCRS} -o run
