
CXX = g++
CXXFLAGS = -std=c++0x
#add CPP files here
SCRS = Barbarian.cpp BlueMen.cpp Creature.cpp Die.cpp HarryPotter.cpp Main.cpp Medusa.cpp Vampire.cpp 
#add HPP files here
HEADERS = Barbarian.hpp BlueMen.hpp Creature.hpp Die.hpp HarryPotter.hpp Medusa.hpp Vampire.hpp


#
#
#
run: ${SCRS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SCRS} -o run
